   caseStudy: synthetic_landslide       # name of the case study, should exist in datasets.config
   problem_type: high_dim_output        # high_dim_input | high_dim_output
   outDir: results                      # name of the output directory
   useGPU: true                        # true/false
   condaEngine: micromamba             # conda/mamba/micromamba
   # The following params are used by high_dim_output workflow
   threshold: 0.5                       # zero-truncation threshold for outputs
   n_components: 20                     # PCA/kPCA components
   latent_dim: 20                       # AE/VAE latent dimension
   qoi: hmax                            # quantity of interest: hmax, vmax, or cmax